Repository DaITssu/daitssu-api, pull requests merged in 2023-10, with the labels that each got.

#67 [#45] 오늘 마감 일정 조회
  src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/TodayCalendarDataDto.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/TodayCalendarResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/model/repository/CalendarRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
  src/test/kotlin/com/example/daitssuapi/domain/course/controller/CourseControllerTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/course/service/CourseServiceTest.kt
  src/test/kotlin/com/example/daitssuapi/unit/domain/course/service/CourseServiceUnitTest.kt
  src/test/resources/h2-data.sql
Labels: 홈화면

#65 [#59] 커뮤니티 - 스크랩 추가하기
  src/main/kotlin/com/example/daitssuapi/common/enums/ErrorCode.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/dto/response/ArticleResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Article.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Scrap.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ScrapRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/service/ArticleService.kt
  src/test/kotlin/com/example/daitssuapi/domain/main/controller/ArticleControllerTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/main/service/ArticleServiceTest.kt
  src/test/resources/h2-data.sql
Labels: 커뮤니티

#71 [공지사항] 댓글 추가
  src/main/kotlin/com/example/daitssuapi/common/enums/ErrorCode.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Comment.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/CommentRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/controller/FunSystemController.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/controller/NoticeController.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/service/FunSystemService.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
  src/test/kotlin/com/example/daitssuapi/domain/main/controller/ArticleControllerTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/main/service/ArticleServiceTest.kt
Labels: 공지사항
