Repository DaITssu/daitssu-api, pull requests merged in 2023-11, with the labels that each got.

#69 [커뮤니티] 게시글 삭제
  src/main/kotlin/com/example/daitssuapi/common/enums/ErrorCode.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/TodayCalendarDataDto.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/TodayCalendarResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/model/repository/CalendarRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
  src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/dto/response/ArticleResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Article.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Comment.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Scrap.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/CommentRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ScrapRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/service/ArticleService.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/controller/FunSystemController.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/controller/NoticeController.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/service/FunSystemService.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
  src/main/resources/application-local.yml
  src/test/kotlin/com/example/daitssuapi/domain/course/controller/CourseControllerTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/course/service/CourseServiceTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/main/controller/ArticleControllerTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/main/service/ArticleServiceTest.kt
  src/test/kotlin/com/example/daitssuapi/unit/domain/course/service/CourseServiceUnitTest.kt
  src/test/resources/h2-data.sql
Labels: 커뮤니티

#68 [커뮤니티] 인기 게시글 조회
  src/main/kotlin/com/example/daitssuapi/common/enums/ErrorCode.kt
  src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/dto/response/ArticleResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Article.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/ArticleLike.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ArticleLikeRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ArticleRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/service/ArticleService.kt
Labels: 커뮤니티

#89 [#75] 닉네임 변경
  src/main/kotlin/com/example/daitssuapi/domain/main/controller/UserController.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/User.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
  src/test/kotlin/com/example/daitssuapi/domain/main/controller/UserControllerTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/main/service/UserServiceTest.kt
  src/test/resources/h2-data.sql
Labels: 마이페이지

#95 공지사항/구독 API 오류 수정
  src/main/kotlin/com/example/daitssuapi/common/enums/FunSystemCategory.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/controller/FunSystemController.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/controller/NoticeController.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/dto/PageFunSystemResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/model/entity/FunSystem.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/model/entity/Notice.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/model/repository/FunSystemRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/model/repository/NoticeRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/service/FunSystemService.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
Labels: bug, 공지사항

#94 [#92] 마이페이지 유저 프로필 등록
  src/main/kotlin/com/example/daitssuapi/common/enums/DomainType.kt
  src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/controller/UserController.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/dto/response/UserResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/User.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
Labels: 마이페이지

#42 Feature/로그인 로직 구현
  src/main/kotlin/com/example/daitssuapi/DaitssuApiApplication.kt
  src/main/kotlin/com/example/daitssuapi/common/enums/ErrorCode.kt
  src/main/kotlin/com/example/daitssuapi/common/security/component/CustomPasswordEncoder.kt
  src/main/kotlin/com/example/daitssuapi/common/security/component/JwtVerifier.kt
  src/main/kotlin/com/example/daitssuapi/common/security/component/TokenParser.kt
  src/main/kotlin/com/example/daitssuapi/common/security/component/TokenProvider.kt
  src/main/kotlin/com/example/daitssuapi/common/security/configuration/AuthorizeRequestsApplierConfiguration.kt
  src/main/kotlin/com/example/daitssuapi/common/security/configuration/SecurityConfiguration.kt
  src/main/kotlin/com/example/daitssuapi/common/security/configuration/TokenAlgorithmConfiguration.kt
  src/main/kotlin/com/example/daitssuapi/common/util/PasswordEncryptionUtil.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/client/SmartCampusCrawlerClient.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/client/request/CrawlBaseInformationRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/client/request/SmartCampusSignInRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/controller/request/ChangePasswordRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/controller/request/RefreshRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/controller/request/SignInRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/controller/request/SignUpRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/controller/response/AuthResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/dto/AuthTokenDto.kt
  src/main/kotlin/com/example/daitssuapi/domain/auth/service/AuthService.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/dto/response/UserResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Department.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/User.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/UserRepository.kt
  src/main/resources/application.yml
  src/test/kotlin/com/example/daitssuapi/unit/domain/course/service/CourseServiceUnitTest.kt
Labels: 서버
