Repository DaITssu/daitssu-api, pull requests merged in 2023-09, with the labels that each got.

#39 [#27] 강의 및 일정 조회 테스트
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/request/AssignmentRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/request/CalendarRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/request/CourseRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/request/VideoRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/AssignmentResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/CalendarResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/CourseResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/VideoResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/model/entity/Calendar.kt
  src/test/kotlin/com/example/daitssuapi/domain/course/controller/CourseControllerTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/course/service/CourseServiceTest.kt
  src/test/kotlin/com/example/daitssuapi/unit/domain/course/service/CourseServiceUnitTest.kt
  src/test/resources/h2-data.sql
Labels: 스마트캠퍼스

#43 [#21] 일정 수정 API
  src/main/kotlin/com/example/daitssuapi/common/enums/ErrorCode.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/request/CalendarRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/CalendarResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/CourseResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/model/entity/Calendar.kt
  src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
  src/test/kotlin/com/example/daitssuapi/domain/course/controller/CourseControllerTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/course/service/CourseServiceTest.kt
  src/test/kotlin/com/example/daitssuapi/unit/domain/course/service/CourseServiceUnitTest.kt
  src/test/resources/h2-data.sql
Labels: 스마트캠퍼스

#41 [#5] 공지사항 펀시스템 api 구현
  src/main/kotlin/com/example/daitssuapi/common/enums/ErrorCode.kt
  src/main/kotlin/com/example/daitssuapi/common/enums/FunSystemCategory.kt
  src/main/kotlin/com/example/daitssuapi/common/enums/NoticeCategory.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/controller/FunSystemController.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/controller/NoticeController.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/dto/FunSystemResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/dto/NoticeResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/model/entity/FunSystem.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/model/entity/Notice.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/model/repository/FunSystemRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/model/repository/NoticeRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/service/FunSystemService.kt
  src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
  src/test/kotlin/com/example/daitssuapi/domain/notice/FunSystemControllerTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/notice/NoticeControllerTest.kt
  src/test/resources/data.sql
  src/test/resources/schema.sql
Labels: 공지사항

#51 Feature/커뮤니티 게시글 검색 기능
  src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/dto/response/PageArticlesResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ArticleRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/service/ArticleService.kt
Labels: 홈화면

#50 Feature/S3-및-이미지-핸들링
  src/main/kotlin/com/example/daitssuapi/common/constants/FileFormat.kt
  src/main/kotlin/com/example/daitssuapi/common/enums/DomainType.kt
  src/main/kotlin/com/example/daitssuapi/common/enums/ErrorCode.kt
  src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/dto/request/ArticleCreateRequest.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/dto/response/ArticleResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/dto/response/PageArticlesResponse.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Article.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/ArticleImage.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ArticleImageRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ArticleRepository.kt
  src/main/kotlin/com/example/daitssuapi/domain/main/service/ArticleService.kt
  src/main/resources/application-local.yml
  src/test/kotlin/com/example/daitssuapi/domain/main/controller/ArticleControllerTest.kt
  src/test/kotlin/com/example/daitssuapi/domain/main/service/ArticleServiceTest.kt
Labels: 커뮤니티
